theme: jekyll-theme-leap-day

name: Cheers Cyber

description: A friendly community for cyber and information security product managers

show_downloads: false

github:
  is_project_page: false
  is_user_page: false
